### ISSUE TITLE
Summary metadata - buckets not being correctly presented or calculated

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper-Plugins/mdm-plugin-database-sqlserver#24]
When the buckets are presented, they can appear to be overlapping:
For integers:
<img width="1122" alt="Screenshot 2023-08-08 at 10 18 33" src="https://github.com/MauroDataMapper-Plugins/mdm-plugin-database-sqlserver/assets/1869668/f546b15e-38d2-4096-a6d6-42653569db9d">

For dates:
<img width="1128" alt="Screenshot 2023-08-08 at 10 18 21" src="https://github.com/MauroDataMapper-Plugins/mdm-plugin-database-sqlserver/assets/1869668/341edd70-b27a-445e-87c4-cec1da24306c">

The ranges should be presented so it's clear where the boundary values lie.  

Also, where the range just contains one number, it should not present that as a range.

**Comment by joe-crawford** [comment]
Fixed by https://github.com/MauroDataMapper/mdm-core/pull/447
