### ISSUE TITLE
Summary metadata - small numbers

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper-Plugins/mdm-plugin-database-sqlserver#25]
There appear to be cases where small numbers are not protected in the summary metadata.  Here is a scrape of the MS NorthWind database with the default settings.  In the screenshot below, the categories with value 1 should be rounded up to 10.

<img width="1533" alt="Screenshot 2023-08-08 at 10 21 52" src="https://github.com/MauroDataMapper-Plugins/mdm-plugin-database-sqlserver/assets/1869668/2ff3440b-0574-4438-b283-6f35cc7453ee">

**Comment by jamesrwelch** [comment]
This could be a new option to the importer - there may be circumstances where you do wish to see small values...

**Comment by joe-crawford** [comment]
In branch `feature/fix-enums-sm`, small numbers are rounded up to the value of `summaryMetadataMinimumValue` (default of 10) as described in https://github.com/MauroDataMapper-Plugins/mdm-plugin-database-sqlserver/issues/26#issuecomment-1753177612.

Example on the `Region` data in the `Customers` class in the Northwind DB:
<img width="1318" alt="Screenshot 2023-10-09 at 16 05 58" src="https://github.com/MauroDataMapper-Plugins/mdm-plugin-database-sqlserver/assets/33897179/50e4e70c-2ac6-4db0-bbb4-29f073df0abe">
