### ISSUE TITLE
Summary metadata - don't calculate when not enough distinct values

### ISSUE THREAD

**Issue by jamesrwelch** [MauroDataMapper-Plugins/mdm-plugin-database-sqlserver#26]
In the summary metadata calculation, there is some logic that stops summary metadata when there are too few distinct rows.  This doesn't always appear to be working:  see for example this from the NorthWind database with default settings:

<img width="1123" alt="Screenshot 2023-08-08 at 10 24 17" src="https://github.com/MauroDataMapper-Plugins/mdm-plugin-database-sqlserver/assets/1869668/8fefd91b-0d04-41ec-a83e-f35f3147b7c2">

**Comment by joe-crawford** [comment]
In branch `feature/fix-enums-sm` of mdm-plugin-database, a new parameter Summary Metadata Minimum Threshold is added (`summaryMetadataMinimumValue`, default is 10).

Summary metadata values less than `summaryMetadataMinimumValue` will be rounded up to this value, and if the (possibly approximate) number of rows in a whole table is less than the value, summary metadata will not be generated.

<img width="974" alt="Screenshot 2023-10-09 at 15 57 28" src="https://github.com/MauroDataMapper-Plugins/mdm-plugin-database-sqlserver/assets/33897179/96eb02c3-b4f7-4ed2-82c6-6e84835a1eb8">
