### ISSUE TITLE
Profile metadata keys should be added for data classes representing SQL views

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper-Plugins/mdm-plugin-database-sqlserver#30]
Views are able to be imported from a SQL Server database and represented as Data Classes. However, while data classes representing tables get profile metadata keys applied (which map to the "MS SQL Table or View" profile), views do not. Therefore any view metadata is not applied.

Also, there is currently no distinction in a data class whether it represents a schema, table or view. Something could be added to the profiles to store this metadata also.

**Comment by joe-crawford** [comment]
Closed by #32
