### ISSUE TITLE
Adjustments to Reference and Enumeration data types created

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper-Plugins/mdm-plugin-database-sqlserver#31]
In its current form, I would like to suggest changes to how Reference and Enumeration types work for the imported data model.

# Reference Types used as foreign key relationships

At the moment, when the SQL Server importer detects a table column which is part of a foreign key, it generates a Mauro `ReferenceType` data type, where the `ReferenceType` data class refers back to the Mauro Data Class that is the base primary table.

For example:

```sql
CREATE TABLE [User] (
    [Id] [int] NOT NULL PRIMARY KEY,
    [Name] [nvarchar](50) NOT NULL
)

CREATE TABLE [UserContact] (
    [Id] [int] NOT NULL PRIMARY KEY,
    [UserId] [int] NOT NULL,
    [Email] [nvarchar](50) NOT NULL,
    [Phone] [nvarchar](50] NOT NULL
)

ALTER TABLE [UserContact] ADD CONSTRAINT [FK_UserContact_User_UserId] FOREIGN KEY ([UserId]) REFERENCES [User].[Id]
```

The above would have a `UserContact` table contain a foreign key back to the `User` table. At the moment, Mauro would generate a Data Type for `UserContact.UserId` similar to:

```json
{
    "id": "333003ea-a941-4a1a-a052-9e4a0fe11d6c",
    "domainType": "ReferenceType",
    "label": "UserContactType",
    "description": "Linked to DataElement [Id]",
    "referenceClass": {
        "id": "0e0532da-46e4-43fd-b401-aa390e15520f",
        "domainType": "DataClass",
        "label": "User",
        "model": "119f36fb-e6b5-457d-b746-cc563f315781",
        "maxMultiplicity": 1,
        "minMultiplicity": 1,
        "parentDataClass": "25548bca-6a81-49b2-999f-ea09ec96222f"
    }
}
```

However, this is not the true SQL type representation of the `UserContact.UserId` field, it should be noted in metadata somehow that it is an `int` field as well.

There is also not a very clear link from the foreign key data element back to it's related primary key data element. Currently, the only way I can see this happening is:

1. Get the `ReferenceType.dataClass` property to find the parent "table"
2. Scan all Data Elements in the parent "table", looking for a metadata/profile key to identify which element was representing the primary key
3. Once the primary key data element is found, using the Mauro data type of that element.

I would like to suggest a couple of changes:

1. The "MS SQL Column" profile should be updated to include a "Foreign Key Base Table" field. There is already a "Foreign Key Columns" field but it does not provide the table name where these fields are located.
2. Add some kind of direct link between two Data Elements in the Data Model so that we can trace the primary key data element back from the foreign key element.

# Enumeration Types retain original data type

When an enumeration type is detected and created, the original primitive type of a data element is removed and lost. Keeping only the enumeration type and values is useful when viewing the metadata, but we've then lost the history of what the original SQL data type was.

As an example, suppose there is a table field called `StatusCode [int]` and this was converted to an `EnumerationType` of distinct values. There is now no metadata or history stating that the data element was originally a set of integers. If the data element was used as a way to generate SQL statements for recreating that database table, we would not know what SQL data type to use based on the metadata currently present.

Perhaps we could:

1. Store the original SQL data type in the "MS SQL Column" profile
2. Maybe add the base primitive type to an enumeration type (if that is even possible). i.e. an `EnumerationType` is based of a `PrimitveType` of `int`.

**Comment by joe-crawford** [comment]
Closed by #32
